package com.example.saryal.howardchat;

/**
 * Created by saryal on 8/7/17.
 */
import com.google.firebase.database.DataSnapshot;

public class Messages {
    private String mContent;
    private String mUserid;
    private String mUsername;

    //local creation
    public Messages(String mContent, String mUserid, String mUsername) {
        this.mContent = mContent;
        this.mUserid = mUserid;
        this.mUsername = mUsername;
        // Note we do not generate a timestamp...that's only generated by the server.
    }

    //firebase entry
    public Messages(DataSnapshot messagesSnapshot) {
        mContent = messagesSnapshot.child("content").getValue(String.class);
        mUserid = messagesSnapshot.child("fromUserId").getValue(String.class);
        mUsername = messagesSnapshot.child("fromUserName").getValue(String.class);
    }
    //getters

    public String getmContent(){return mContent;}
    public String getmUserid(){return mUserid;}
    public String getmUsername(){return mUsername;}
}

